### ISSUE TITLE
Which meta-rockchip dependency?

### ISSUE THREAD

**Issue by Bastian-Krause** [iesy-gmbh/meta-iesy-osm#2]
https://github.com/iesy-gmbh/meta-iesy-osm/blob/dd32ddf0a7415be6ebdf43e79a032c33b3c3043d/README.md#L8

There are two meta-rockchip layers:

https://git.yoctoproject.org/meta-rockchip/
https://github.com/JeffyCN/meta-rockchip (I guess that one was https://github.com/rockchip-linux/meta-rockchip before?)

Which one should be used here?

**Comment by StefanLellwitz** [comment]
Hi ;)
Indeed it was rockchip-linux/meta-rockchip and now it's JeffyCN/meta-rockchip. (see [iesy-osm-rpx30.xml](https://github.com/iesy-gmbh/yocto-bsp-manifest/blob/dunfell/iesy-osm-rpx30.xml#L16))

**Comment by Bastian-Krause** [comment]
Thanks for the clarification!
